# docker-compose 进行多容器管理和运行
version: "3.7" # 这个是配置文件的版本，不同的版本号声明方式会有细微的不同
services:
    info:
        container_name: pea3nut-info
        image: pea3nut/pea3nut-info:latest
        ports:
            - "8082:80"
        restart: on-failure